### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dataset' of null

### ISSUE THREAD

**Issue by Magic947** [C0bra5/starbound-open-unsupported-files#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Unknown Windows version
**Thrown From**: [starbound-open-unsupported-files](https://github.com/C0bra5/starbound-open-unsupported-files) package 2.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'dataset' of null

```
At C:\Users\coulotda\.atom\packages\starbound-open-unsupported-files\lib\main.js:29

TypeError: Cannot read property 'dataset' of null
    at Object.onTreeViewEntryClicked (/packages/starbound-open-unsupported-files/lib/main.js:29:51)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.56.0/resources/app/static/<embedded>:14:980070)
```

### Commands

```
     -1:44.1.0 application:reopen-project (div#add-projects-view.)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
busy 0.7.0 
css-color-name 0.4.0 
jurassic_systems-ui 0.1.3 
linter 3.3.1 
starbound-autocomplete-json 3.2.0 
starbound-autocomplete-lua 1.4.3 
starbound-build 1.5.0 
starbound-language-json 1.2.1 
starbound-language-lua 1.0.0 
starbound-linter-json 1.1.1 
starbound-linter-lua 2.0.11 
starbound-modding-suite 1.0.10 
starbound-open-unsupported-files 2.0.1 
starbound-pretty-json 1.0.0 
```

**Comment by Magic947** [comment]
Juste double-click on a php file on atom application

**Comment by AbsoluteXeroEX** [comment]
Values are no longer getting passed properly to **onTreeViewEntryClicked(e)** _(undefined)_; e.detail results in "1" when it's looking for another value besides. Could possibly be related to the latest Atom 1.57 update.

**Comment by C0bra5** [comment]
The issue should be fixed now, sorry for the delay.
